version: "3.3"
services:
  redis:
    image: redis:5.0.14
    restart: unless-stopped
    volumes: 
      - cache:/data
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=foopassword
      - MYSQL_DATABASE=fbets
      - MYSQL_USER=fb
      - MYSQL_PASSWORD=password
    volumes:
      - ./sql_init:/docker-entrypoint-initdb.d
      - db:/var/lib/mysql
  mongodb:
    image: mongo:3.6.8
    volumes: 
      - mongo:/data/db
  app:
    build:
        context: .
        dockerfile: Dockerfile
    links:
        - redis:redishost
        - mysqldb:dbhost
        - mongodb:mongohost
    depends_on:
        - mysqldb
        - mongodb
        - redis
    restart: unless-stopped
    env_file: .env
    ports:
      - 80:8080/tcp
    volumes:
      - ./log:/usr/src/friendly-football-bets/log
volumes:
  db:
  cache:
  mongo:
