version: "3.3"
services:
  redis:
    image: redis:5.0.14
    restart: unless-stopped
    volumes: 
      - cache:/data
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=foopassword
      - MYSQL_DATABASE=fbets
      - MYSQL_USER=fb
      - MYSQL_PASSWORD=password
    volumes:
      - ./sql_init:/docker-entrypoint-initdb.d
      - db:/var/lib/mysql
  mongodb:
    image: mongo:4.4.13
    volumes: 
      - mongo:/data/db
  app:
    build:
        context: .
        dockerfile: Dockerfile
    links:
        - redis:redishost
        - mysqldb:dbhost
        - mongodb:mongohost
    depends_on:
        - mysqldb
        - mongodb
        - redis
    restart: unless-stopped
    env_file: .env
    deploy:
      replicas: 5
    volumes:
      - /var/log/ffb:/usr/src/friendly-football-bets/ffb_server/log
      - /var/www/ffb/assets:/usr/src/friendly-football-bets/ffb_server/assets
  nginx:
    links:
        - app:app
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /var/log/nginx:/var/log/nginx
    ports:
      - 80:80
volumes:
  db:
  cache:
  mongo:
