version: "3.3"
services:
  redis:
    image: redis:7.0.2
    restart: unless-stopped
    volumes: 
      - cache:/data
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=foopassword
      - MYSQL_DATABASE=fbets
      - MYSQL_USER=fb
      - MYSQL_PASSWORD=password
    volumes:
      - ./sql_init:/docker-entrypoint-initdb.d
      - db:/var/lib/mysql
  mongodb:
    image: mongo:4.4.14
    volumes: 
      - mongo:/data/db
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    restart: unless-stopped
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  app:
    build:
        context: .
        dockerfile: Dockerfile
    links:
        - redis:redishost
        - mysqldb:dbhost
        - mongodb:mongohost
        - elasticsearch:elastichost
    depends_on:
        - mysqldb
        - mongodb
        - redis
        - elasticsearch
    restart: unless-stopped
    env_file: .env
    deploy:
      replicas: 5
    volumes:
      - /var/log/ffb:/usr/src/friendly-football-bets/ffb_server/log
      - ffb_assets:/usr/src/friendly-football-bets/ffb_server/assets
  nginx:
    links:
        - app:app
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /var/log/nginx:/var/log/nginx
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - 80:80
      - 443:443
volumes:
  db:
  cache:
  mongo:
  elasticsearch-data:
  ffb_assets:
