//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

pub mod prelude;

pub mod club;
pub mod competition;
pub mod edition;
pub mod federation;
pub mod federation_club;
pub mod game;
pub mod navaccess;
pub mod role;
pub mod role_navaccess;
pub mod sea_orm_active_enums;
pub mod seaql_migrations;
pub mod stadium;
pub mod user;
pub mod user_fav_club;
