//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "FEDERATION_CLUB")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub federation_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub club_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::club::Entity",
        from = "Column::ClubId",
        to = "super::club::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Club,
    #[sea_orm(
        belongs_to = "super::federation::Entity",
        from = "Column::FederationId",
        to = "super::federation::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Federation,
}

impl Related<super::club::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Club.def()
    }
}

impl Related<super::federation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Federation.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
