//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

pub mod prelude;

pub mod blacklist;
pub mod navaccess;
pub mod requester;
pub mod role;
pub mod role_navaccess;
pub mod seaql_migrations;
pub mod user;
