//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

pub use super::navaccess::Entity as Navaccess;
pub use super::role::Entity as Role;
pub use super::role_navaccess::Entity as RoleNavaccess;
pub use super::seaql_migrations::Entity as SeaqlMigrations;
pub use super::user::Entity as User;
