//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

pub use super::club::Entity as Club;
pub use super::competition::Entity as Competition;
pub use super::edition::Entity as Edition;
pub use super::federation::Entity as Federation;
pub use super::federation_club::Entity as FederationClub;
pub use super::game::Entity as Game;
pub use super::navaccess::Entity as Navaccess;
pub use super::role::Entity as Role;
pub use super::role_navaccess::Entity as RoleNavaccess;
pub use super::seaql_migrations::Entity as SeaqlMigrations;
pub use super::stadium::Entity as Stadium;
pub use super::user::Entity as User;
