//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "FEDERATION")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::competition::Entity")]
    Competition,
    #[sea_orm(has_many = "super::federation_club::Entity")]
    FederationClub,
}

impl Related<super::competition::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Competition.def()
    }
}

impl Related<super::federation_club::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FederationClub.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
