//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "COMPETITION")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub federation_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::federation::Entity",
        from = "Column::FederationId",
        to = "super::federation::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Federation,
    #[sea_orm(has_many = "super::edition::Entity")]
    Edition,
}

impl Related<super::federation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Federation.def()
    }
}

impl Related<super::edition::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Edition.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
